<?xml version="1.0"?>
<robot name="zalpiano" xmlns:xacro="http://ros.org/wiki/xacro">


  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.51"/>
  <xacro:property name="base_length" value="0.51"/>
  <xacro:property name="base_height" value="0.98"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.02"/>
  <xacro:property name="wheel_zoff" value="0.49"/> <!-- half of base height for wheel axis placement to be on bottom of robot -->
  <xacro:property name="wheel_xoff" value="0.0"/>

  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- BASE (Body) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  
  <!-- FOOTPRINT (this should be projected onto the ground, take care of the z values) -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  
  <!-- WHEELS -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  
  <!-- CASTER WHEEL -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>

  <link name="back_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="back_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster"/>
    <origin xyz="${-caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>

  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  
  <!-- ArUco Marker 0 -->
  <link name="aruco_marker_0_link">
    <visual>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
      <material name="Aruco0">
        <!-- color for RVIZ-->
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
    </collision>

  </link>

  <joint name="base_to_aruco_marker_0" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_marker_0_link"/>
    <origin xyz="0.185 0 ${(base_height)/2}" rpy="0 0 0"/>
  </joint>

  <!-- ArUco Marker 1 -->
  <link name="aruco_marker_1_link">
    <visual>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
      <material name="Aruco1">
        <!-- color for RVIZ-->
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
    </collision>

  </link>

  <joint name="base_to_aruco_marker_1" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_marker_1_link"/>
    <origin xyz="0 0.185 ${(base_height)/2}" rpy="0 0 0"/>
  </joint>

  <!-- ArUco Marker 2 -->
  <link name="aruco_marker_2_link">
    <visual>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
      <material name="Aruco2">
        <!-- color for RVIZ-->
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
    </collision>

  </link>

  <joint name="base_to_aruco_marker_2" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_marker_2_link"/>
    <origin xyz="-0.185 0 ${(base_height)/2}" rpy="0 0 0"/>
  </joint>

  <!-- ArUco Marker 3 -->
  <link name="aruco_marker_3_link">
    <visual>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
      <material name="Aruco3">
        <!-- color for RVIZ-->
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.001"/>
      </geometry>
    </collision>

  </link>

  <joint name="base_to_aruco_marker_3" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_marker_3_link"/>
    <origin xyz="0 -0.185 ${(base_height)/2}" rpy="0 0 0"/>
  </joint>

  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////////////////// -->

  <link name="aruco_center_link0">
  </link>

  <joint name="center_to_aruco_marker_0" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_center_link0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="aruco_center_link1">
  </link>

  <joint name="center_to_aruco_marker_1" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_center_link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="aruco_center_link2">
  </link>

  <joint name="center_to_aruco_marker_2" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_center_link2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="aruco_center_link3">
  </link>

  <joint name="center_to_aruco_marker_3" type="fixed">
    <parent link="base_link"/>
    <child link="aruco_center_link3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>