controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    zalpiano_base_controller:
      type: diff_drive_controller/DiffDriveController

zalpiano_base_controller:
  ros__parameters:
    # left_wheel_names: ["left_wheel_joint"]
    # right_wheel_names: ["right_wheel_joint"]
    left_wheel_names: ["drivewhl_l_joint"]
    right_wheel_names: ["drivewhl_r_joint"]

    # wheel_separation: 0.10
    #Tape measure shows 0.64m
    wheel_separation: 0.64

    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.10

    wheel_separation_multiplier: 1.0
    
    #set one of these to a negative value to change direction
    #set them to 0.1 for a gear ratio of 1:10
    left_wheel_radius_multiplier: -0.1
    right_wheel_radius_multiplier: 0.1

    publish_rate: 100.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0
    linear.x.min_velocity: -3.0
    linear.x.max_acceleration: 20.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 5.0
    angular.z.min_acceleration: -5.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
